name: 🚀 Deploy caterly-admin cpanel(PAT)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🚀 Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            echo "🚀 Starting Deployment..."

            cd ~/public_html/test/caterly_admin

            echo "🔐 Setting Git with PAT"
            git config --global credential.helper store

            echo "https://${{ secrets.GH_USERNAME }}:${{ secrets.GH_PAT }}@github.com" > ~/.git-credentials

            echo "📥 Pull latest code"
            git fetch --all
            git reset --hard origin/main

            echo "🧹 Cleaning old build"
            rm -rf .next

            echo "📦 Installing dependencies"
            npm install --legacy-peer-deps

            echo "🏗 Building project"
            npm run build

            echo "🔄 Restarting PM2"

            pm2 delete caterly-admin || true 
            
            echo "🚀 Starting NestJS app from dist/main.js" 
            PORT=3120 pm2 start npm --name "caterly-admin" -- run start

            pm2 save

            pm2 list

            echo "✅ Deployment Completed!"
